#!/bin/bash

# Read pyWal colors (strip #)
BG=$(sed -n '1p' ~/.cache/wal/colors | sed 's/#//')
ACCENT=$(sed -n '4p' ~/.cache/wal/colors | sed 's/#//')
FG=$(sed -n '8p' ~/.cache/wal/colors | sed 's/#//')

cat > ~/.config/hypr/wal.conf <<EOF
# Auto-generated by pyWal
\$bg = rgba(${BG}ff)
\$accent = rgba(${ACCENT}ff)
\$fg = rgba(${FG}ff)
EOF
